obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
#ifdef CONFIG_VENDOR_EDIT
#/* Zhangchangan  PSW.BSP.CHG  2019-10-30 */
obj-$(CONFIG_VENDOR_EDIT)	+= oppo/
#endif
